### ISSUE TITLE
Wrong region displayed when using `-r` and dmabuf backend on screen with display scaling 2

### ISSUE THREAD

**Issue by akselaase** [Ferdi265/wl-mirror#13]
Hi, thank you for the great utility.

I noticed an issue where the wrong region is mirrored when passing in region coordinates with `-r` on the dmabuf backend on my 3000x2000 laptop screen with display scaling 2. It seems that the region I specify (in the scaled coordinate space of size 1500x1000) is wrongly interpreted in the unscaled coordinate system (with size 3000x2000).

With `-b screencopy` it displays correctly, and changing the display scaling to 1 also fixes the problem.

Version info:
```
wl-mirror v0.12.1
sway version 1.7
```

I've been using this command to select regions with `slurp`:

```
swaymsg -t get_tree | \
    jq -r  '.. | (.nodes? // empty)[] | select(.pid and .visible) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | \
    slurp -r -o | \
    xargs -d "\n" wl-mirror -b dmabuf -r
```

**Comment by Ferdi265** [comment]
Thanks for the bug report and for the detailed reproduction instructions!

I'll try to reproduce this tomorrow. I don't usually use scaled monitors a lot, so that might explain why I missed an edge case. The bug does not sound hard to fix, so if I manage to reproduce this, you can probably expect a fix to be released before the weekend.

**Comment by Ferdi265** [comment]
Decided to look at this right now, and immediately reproduced it.

It turns out I never tested regions with scaling since the last major refactor. I simply forgot to scale the region to the current output scale for the texture coordinate transform.

The screencopy backend worked fine because that backend is region aware and communicates the region to the compositor, so the texture buffer already contains a correctly cropped image, while dmabuf always gives you the whole screen and the cropping is done in post before rendering.

I'll push out a 0.12.2 release in the next few days. In the meantime you can use `wl-mirror-git` from the AUR (if you're on arch) or build it yourself.

**Comment by akselaase** [comment]
Amazing, thank you for the quick response and fix!
