### ISSUE TITLE
Support freezing / unfreezing the mirrored screen

### ISSUE THREAD

**Issue by dR3b** [Ferdi265/wl-mirror#18]
I would like to have an option to freeze the image (space key?). Especially for presentations would be an advantage.

**Comment by dR3b** [comment]
Thanks! I compiled the `main` branch and voila it works!

**Comment by Ferdi265** [comment]
I have now implemented texture copying, though it seems to not work perfectly well. Copying the texture in the way that I do it does not seem to work with dmabuf, but now it at least displays a black screen instead of not freezing at all with dmabuf. The screencopy backend should work just as well as before.

**Comment by Ferdi265** [comment]
It seems copying the texture fails with a `GL_INVALID_OPERATION` with the dmabuf backend. I know too little about OpenGL to fix this at present. I also tried to experiment with something like doing a complete render to texture, but that would need more time to do properly, and I didn't get it to work on a first hacky try.

**Comment by Ferdi265** [comment]
I fixed it: the texture format was wrong. Ideally, I would want to query the actual format and use that, but that is a GLES3.1 feature, and for now I want to stay at only requiring GLES2.0.

The "fix" was using GL_RGB8_OES, which seems to work for both screencopy and dmabuf, but in the long run finding a way to get the actual texture format is probably a good idea.

**Comment by Ferdi265** [comment]
Since screencopy actually _knows_ the GL format (there is a whole table for translating shm to gl formats), each backend now stores the gl format it uses into a variable, so the common code doesn't have to guess.

the dmabuf backend still has to guess, though I guess at some point we can figure out how to get the correct gl format from the drm fourcc format code.

For this reason I'll release this as-is, and leave the "correct" fix for dmabuf format codes for later. If anyone can reproduce a case where `--freeze` does not work correctly with the dmabuf backend, let me know and open an issue.

**Comment by dR3b** [comment]
Thanks!
