### ISSUE TITLE
Mirror a region of the screen

### ISSUE THREAD

**Issue by victordiaz** [Ferdi265/wl-mirror#2]
It would be nice to pass some coordinates to `wl-mirror` that defines a rectangle to mirror. (see `slurp` command).
A lot of interesting workflows could arise combining it with `swaywm` virtual outputs 

(reference) https://www.reddit.com/r/swaywm/comments/k1zl41/thank_you_devs_free_ipad_repurposed_as_a_second/

**Comment by Ferdi265** [comment]
I'll definitely implement this, since it isn't too hard and provides a very useful feature, however getting it to work with with `slurp` requires me to save a little more information about the outputs:

Roadmap:
- [ ] add slurp region parsing
- [ ] save `xdg_output` logical position and logical size
- [ ] transform slurp region into texture coordinates
- [ ] clamp slurp region to texture boundaries
- [ ] calculate texture coordinate transform
- [ ] set viewport to slurp region
- [ ] apply texture coordinate transform

I might be able to fit this in this week, but if not, I'll definitely try to do it on the weekend.

**Comment by Ferdi265** [comment]
Implementing the region parsing and the region transform is turning out to be more complicated than I thought, so I'm going to release the output transform support now and postpone this to v0.5.0

**Comment by Ferdi265** [comment]
Implemented as of e0d6cdf. I'll do a bit more testing tomorrow and will probably release v0.5.0 then.
