### ISSUE TITLE
Clarification on license

### ISSUE THREAD

**Issue by dvzrv** [Ferdi265/wl-mirror#27]
Hi! I package this project for Arch Linux. As we are now using SPDX license identifiers, could you please clarify whether the work on this project has been covered under the [GPL-3.0-only](https://spdx.org/licenses/GPL-3.0-only.html) or [GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later.html)? The README unfortunately does not specify this and all I have to go on currently is the license file itself.

FTR: I believe in the latter case you may have to ask any previous/current contributors whether it is fine to relicense their work under that license, too.

**Comment by Ferdi265** [comment]
You are correct in that — up until now — I have failed to clarify whether the license is GPL-3.0-only or GPL-3.0-or-later. The license file itself is also just a direct copy of the GPL-3.0 from [choosealicense.com](https://choosealicense.com), which, from a cursory glance at the license text, does not specify whether it is only GPL-3.0, GPL-3.0-or-later, or *any* GPL version. (There is a paragraph that describes what happens if the project specifies such a detail)

I will conduct a poll with the other 3 contributors on the exact licensing (GPL-3.0-or-later vs GPL-3.0-only) to decide on how exactly to go forward and will add a License section to the README as a result of that poll.

Currently I think I am more situated towards GPL-3.0-or-later, but until that poll is done, I'm not sure if I can just choose.

**Comment by Ferdi265** [comment]
@rbo @jbeich @dvzrv Would you be okay with licensing this project as GPL-3.0-or-later?

**Comment by Ferdi265** [comment]
AIUI, in the meantime, as the project currently exists, the fact that the LICENSE file is GPL-3.0, without any other explicit notes, until this relicensing poll is finished, the license is effectively GPL-3.0-only.

**Comment by Ferdi265** [comment]
TODO for whatever the result of this poll is: Recheck packaged versions of wl-mirror and adjust the license if necessary.

**Comment by rbo** [comment]
Fine for me – thanks for asking.

**Comment by jbeich** [comment]
OK for me.

**Comment by dvzrv** [comment]
I'm of course also fine with the change/clarification! :)
