### ISSUE TITLE
Option to start in fullscreen

### ISSUE THREAD

**Issue by aylurus** [Ferdi265/wl-mirror#30]
It would be useful if there was an option to start wl-mirror in fullscreen. Sometimes during presentations, I need to show something interactively. wl-mirror is very useful for this. I configured sway with shortcuts to open/close wl-mirror on the external output. Opening it on the right output is easily achieved by setting the focus before launching wl-mirror. But automatically getting it fullscreen requires some trickery, e.g. moving to an empty workspace first to force it into focus after launching and then triggering fullscreen. This does not seem very clean, as it requires the fullscreen command to be timed correctly and requires additional effort to restore the previous context of the external output after closing wl-mirror. Adding an option to start in fullscreen would simplify this use case and make wl-mirror even more handy.

**Comment by Ferdi265** [comment]
Hi! Yes, I can easily add a `--fullscreen` option that uses the `set_fullscreen(output)` XDG Shell request. Given that getting the window fullscreen on the correct output via desktop environment config is difficult, that option is definitely useful.

I could also add a `--fullscreen-output` option to directly specify which output to fullscreen on (if not given, default to the current output), which would simplify your config even more, and might make use of this feature more portable to less configurable compositors (once XDG Portal screen share is implemented properly).

**Comment by aylurus** [comment]
Those options would be very nice! It's not relevant to my use case, but maybe it would be more flexible to separate the fullscreen and output options? (If it doesn't make the implementation more complicated.)

**Comment by Ferdi265** [comment]
the `--fullscreen-output` option is for specifying an output to fullscreen on. On Wayland, applications can't choose an output they want to be displayed on except when fullscreening, so it's not possible to implement an option that selects which output wl-mirror should appear on without it going fullscreen

**Comment by Ferdi265** [comment]
AFAIUI, fullscreen-shell is mainly intended as a replacement for applications and games that want to do oldschool "fullscreen at a specific resolution", resulting in a display modeset (present_for_mode), and alternatively fullscreen with some options for controlling how the surface is scaled to screen size (present). It's basically a lower-level version of xdg-shell fullscreen with more feedback and control.

I have not used the protocol yet, but I would expect that the fullscreen state can be cancelled the same way as an xdg-shell fullscreen state. It would be interesting to test whether the behaviour differs from xdg-shell fullscreen when using client-side decorations with libdecor (not merged yet, see branch feature-libdecor), since we probably do not want the title bar to be visible in fullscreen.

Implementation-wise, this should not be that much more work than xdg shell fullscreen. Both require the same plumbing work in `src/options.c` and after initially creating a window (probably in `src/wayland.c`), and fullscreen-shell requires just one additional set of event handlers to handle compositor feedback to the fullscreen operation.

@SoumyaRanjanPatnaik if you want, you can have a go at implementing this. I recently added a `next` branch to the repository, so please choose this as a target for the pull request if you create one. (that reminds me I still need to add contribution guidelines to the repo README)

**Comment by SoumyaRanjanPatnaik** [comment]
Hey. Gave this a try. Apparently, sway doesn't support fullscreen-shell since it is an unstable protocol, so I was (sadly) unable to bind to `zwp_fullscreen_shell_v1`.  Can we instead use `wlr_layer_shell` ?   I know we can anchor the surface to all the edges of an output to essentially fullscreen the surface. I'm not sure if this is a good idea, but I'd really like a way to essentially pin `wl-mirror` to an output. 

Regardless using set_fullscreen() on xdg_toplevel does in fact work. It was a one-line change(excluding the parsing of options) and I'm mostly happy with the way it works.

**Comment by SoumyaRanjanPatnaik** [comment]
BTW, if you want, I can make a PR for this using `xdg_toplevel_set_fullscreen`.

**Comment by Ferdi265** [comment]
fixed by #31 and released in 0.15.0

**Comment by aylurus** [comment]
Thank you very much! Let me know if there is some way to financially support the project.

**Comment by Ferdi265** [comment]
Thank _you_ for the feature request!

Up until now I didn't have any easy way for people to support me, but I just set up a [Ko-fi](https://ko-fi.com/ferdi265) if you do want to support the project financially. Also, I want to add that part of the credit for this feature goes to @SoumyaRanjanPatnaik who basically implemented most of the feature. Thank you so much @SoumyaRanjanPatnaik :)

**Comment by SoumyaRanjanPatnaik** [comment]
Thanks for the credit @Ferdi265 😊. I was looking for a way for `wl-mirror` to be the only surface displayed on my secondary display. I was already prepared to try and implement that. This issue was a happy accident.
