### ISSUE TITLE
Support for automatically detecting fuzzel in wl-present

### ISSUE THREAD

**Issue by feinedsquirrel** [Ferdi265/wl-mirror#40]
I'm not sure if `fuzzel` (https://codeberg.org/dnkl/fuzzel) has the capability necessary. I'm not in a position to dig into it at the moment.

`wl-present` optionally requires `rofi`, and when I switched from xorg to wayland I moved from `rofi` to `fuzzel`. I do have the impression that `fuzzel` doesn't have quite all the features of `rofi`, so this may not be possible.

**Comment by Ferdi265** [comment]
This is easily possible since version 0.16.2 of `wl-present`: Just `export WL_PRESENT_DMENU="fuzzel -d"` somewhere in your environment settings (profile, rc files, DE settings, ...).

`wl-present` is compatible with all dmenu-compatible menu/launchers, and it has automatic detection for a few that I know of.

I'll gladly accept a patch that adds `fuzzel` to the list of automatically detected dmenu implementations, just add it to `scripts/wl-present` in the if/elif chain starting at line 33 (and the help string at line 25)

**Comment by Ferdi265** [comment]
@feinedsquirrel I merged your branch autodetecting `fuzzel` since it seemed pretty complete and added documentation for it.

Fixed in 8a4eac5.

**Comment by Ferdi265** [comment]
Released in 0.16.4

**Comment by feinedsquirrel** [comment]
Yes, this is great! Thank you for the guidance on what to change. I was waiting to test it before creating the pull request. I was finally able to test it yesterday; it all worked well, and got back to checking on this commit today.
Thanks again!
