### ISSUE TITLE
How to support

### ISSUE THREAD

**Issue by minnten** [Ferdi265/wl-mirror#56]
Hello @Ferdi265,

I am a teacher and very interested in wl-mirror, especially when it finally works under Gnome. 

My question is:  how I can best support you.
I couldn't find any donation links or similar things where someone like me could support.

Unfortunately, I can contribute nothing more in terms of programming. However, if desired, I would be happy to take over tests for Gnome (under NixOS). The package I've already found is ready to build, adjusted so far that I can get a successful build with the current git-state. 

Best regards, 

Minnten

**Comment by Ferdi265** [comment]
Hi!

Thanks for the interest in wl-mirror!

Regarding donations: I have a link to my [ko-fi](https://ko-fi.com/ferdi265) page on my GitHub profile, but haven't added it to any project specific pages yet.

I currently don't have a lot of time to work on wl-mirror, since I work 20h on the side and still have to finish my university degree, but I try to get a bit of wl-mirror work in once a week. I can't guarantee the Gnome support will be done soon, but I'll try to get it at least cleaned up into a more usable state before Christmas.

If you want to test it, the current state of KDE/Gnome support in wl-mirror is in [this PR](https://github.com/Ferdi265/wl-mirror/pull/47), but to test it you'd also need to enable` -DWITH_LIBDECOR=ON` and `-DWITH_XDG_PORTAL_BACKEND=ON` to the CMake argument list in the nix package, as well as add `pipewire` and `systemdLibs` (or `basu`) to dependencies/build inputs (probably, I don't really use nixOS, but this is what a quick google search brought up).

After that, you should be able to run `wl-mirror -b xdg-portal eDP-1` and it should open the standard Gnome popup for screen share target selection (you currently have to pass an (ignored) output name on the CLI as well since I haven't adjusted the argument parsing for it yet).

This is currently preview quality and likely won't work on many GPU setups, since image format negotiation is completely missing, which I need to implement still. It didn't work properly on Intel when I first wrote it, but it seems to have started working on AMDGPU without me changing anything recently.

**Comment by minnten** [comment]
Thanks I will try it out
