### ISSUE TITLE
Include protocols in release tarballs

### ISSUE THREAD

**Issue by sochotnicky** [Ferdi265/wl-mirror#6]
wlr-protocols are generally not packaged in distributions (there's not even a release, even wlroots itself copies what it needs (see https://gitlab.freedesktop.org/wlroots/wlroots/-/tree/master/protocol). 

IMO It would be better if you included the protocols you need - at least in the release tarballs. Though you might want to consider making a copy of needed protocols just like wlroots itself does even in the git repo. After all - it's not very likely to change all that much.

**Comment by Ferdi265** [comment]
Since GitHub does not support having submodules be part of the source code download, every release already contains a tarball with the name `wl-mirror-$VERSION.tar.gz` that contains a clone of the protocols used in that release inside the `proto/` subdirectory.

So if I understand your suggestion correctly, that is already implemented.
I do it slightly differently in that I do not ship the protocols as part of the repo, but as part of a submodule, but that's why I also put them into the release tarballs.

(will close this issue if I get confirmation that this is what you mean)

**Comment by sochotnicky** [comment]
A-ha! I totally missed the release tarball and just downloaded the tag tarball (which doesn't have the submodule data).

So you are right, all's good. I just missed the release tarball..

**Comment by Ferdi265** [comment]
There definitely is something I learned from this issue though: The README needs some work ;)
